/* GENERATED by scripts/openont/gen-buckets.py — do not edit */
#ifndef OPENONT_BUCKETS_GEN_H
#define OPENONT_BUCKETS_GEN_H
#include <stdint.h>
#include <string.h>
#define OPENONT_DPI_MARK_SHIFT 16
#define OPENONT_DPI_MARK_MASK  0x00FF0000u
enum oo_bucket_id {
	OO_B_UNKNOWN = 0,
	OO_B_HTTP = 1,
	OO_B_VIDEO = 2,
	OO_B_GAME = 3,
	OO_B_DOWNLOAD = 4,
	OO_B_FILE = 5,
	OO_B_IM = 6,
	OO_B_COMMON = 7,
	OO_B_OTHER_APP = 8,
	OO_B_SPEEDTEST = 9,
};
static inline const char *oo_bucket_name(uint8_t id)
{
	switch (id) {
	case 0: return "unknown";
	case 1: return "http";
	case 2: return "video";
	case 3: return "game";
	case 4: return "download";
	case 5: return "file";
	case 6: return "im";
	case 7: return "common";
	case 8: return "other_app";
	case 9: return "speedtest";
	default: return "unknown";
	}
}
static inline uint8_t oo_bucket_id(const char *name)
{
	if (!name || !*name) return 0;
	if (!strcmp(name, "unknown")) return 0;
	if (!strcmp(name, "http")) return 1;
	if (!strcmp(name, "video")) return 2;
	if (!strcmp(name, "game")) return 3;
	if (!strcmp(name, "download")) return 4;
	if (!strcmp(name, "file")) return 5;
	if (!strcmp(name, "im")) return 6;
	if (!strcmp(name, "common")) return 7;
	if (!strcmp(name, "other_app")) return 8;
	if (!strcmp(name, "speedtest")) return 9;
	return 0;
}
#endif
