# GENERATED by scripts/openont/gen-buckets.py — do not edit
OPENONT_DPI_MARK_SHIFT=16
OPENONT_DPI_MARK_MASK=0x00FF0000
OPENONT_BUCKET_NAMES="unknown http video game download file im common other_app speedtest"
openont_bid2name() {
	case "$1" in
	0) echo unknown ;;
	1) echo http ;;
	2) echo video ;;
	3) echo game ;;
	4) echo download ;;
	5) echo file ;;
	6) echo im ;;
	7) echo common ;;
	8) echo other_app ;;
	9) echo speedtest ;;
	*) echo unknown ;;
	esac
}
