#!/usr/bin/env python3
"""Generate buckets.gen.h, buckets.sh, buckets.json from buckets.schema."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "package/openont/openont-stats/files/usr/share/openont/buckets.schema"
OUT_DIR = ROOT / "package/openont/openont-stats/files/usr/share/openont"
DPI_INC = ROOT / "package/openont/openont-dpi/src"
JS_OUT = ROOT / "package/openont/luci-mod-openont/htdocs/luci-static/resources/openont/buckets.json"


def load_rows(path: Path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("|")
        if len(parts) < 3:
            continue
        rows.append((parts[0].strip(), parts[1].strip(), parts[2].strip()))
    return rows


def sym(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]", "_", name.upper())
    return s


def main() -> int:
    if not SCHEMA.is_file():
        print(f"missing schema: {SCHEMA}", file=sys.stderr)
        return 1
    rows = load_rows(SCHEMA)
    if not rows:
        print("no buckets in schema", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DPI_INC.mkdir(parents=True, exist_ok=True)
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)

    h = [
        "/* GENERATED by scripts/openont/gen-buckets.py — do not edit */",
        "#ifndef OPENONT_BUCKETS_GEN_H",
        "#define OPENONT_BUCKETS_GEN_H",
        "#include <stdint.h>",
        "#include <string.h>",
        "#define OPENONT_DPI_MARK_SHIFT 16",
        "#define OPENONT_DPI_MARK_MASK  0x00FF0000u",
        "enum oo_bucket_id {",
    ]
    for i, name, _c in rows:
        h.append(f"\tOO_B_{sym(name)} = {i},")
    h += [
        "};",
        "static inline const char *oo_bucket_name(uint8_t id)",
        "{",
        "\tswitch (id) {",
    ]
    for i, name, _c in rows:
        h.append(f'\tcase {i}: return "{name}";')
    h += [
        '\tdefault: return "unknown";',
        "\t}",
        "}",
        "static inline uint8_t oo_bucket_id(const char *name)",
        "{",
        "\tif (!name || !*name) return 0;",
    ]
    for i, name, _c in rows:
        h.append(f'\tif (!strcmp(name, "{name}")) return {i};')
    h += ["\treturn 0;", "}", "#endif", ""]
    h_text = "\n".join(h)
    (OUT_DIR / "buckets.gen.h").write_text(h_text, encoding="utf-8", newline="\n")
    (DPI_INC / "buckets.gen.h").write_text(h_text, encoding="utf-8", newline="\n")

    sh = [
        "# GENERATED by scripts/openont/gen-buckets.py — do not edit",
        "OPENONT_DPI_MARK_SHIFT=16",
        "OPENONT_DPI_MARK_MASK=0x00FF0000",
        'OPENONT_BUCKET_NAMES="' + " ".join(n for _, n, _ in rows) + '"',
        "openont_bid2name() {",
        '\tcase "$1" in',
    ]
    # fix case syntax
    sh = [
        "# GENERATED by scripts/openont/gen-buckets.py — do not edit",
        "OPENONT_DPI_MARK_SHIFT=16",
        "OPENONT_DPI_MARK_MASK=0x00FF0000",
        'OPENONT_BUCKET_NAMES="' + " ".join(n for _, n, _ in rows) + '"',
        "openont_bid2name() {",
        '	case "$1" in',
    ]
    for i, name, _c in rows:
        sh.append(f"	{i}) echo {name} ;;")
    sh += ["	*) echo unknown ;;", "	esac", "}", ""]
    (OUT_DIR / "buckets.sh").write_text("\n".join(sh), encoding="utf-8", newline="\n")

    obj = {
        "mark_shift": 16,
        "buckets": [{"id": int(i), "name": n, "color": c} for i, n, c in rows],
    }
    jtxt = json.dumps(obj, indent=2) + "\n"
    (OUT_DIR / "buckets.json").write_text(jtxt, encoding="utf-8", newline="\n")
    JS_OUT.write_text(jtxt, encoding="utf-8", newline="\n")

    print(f"generated {len(rows)} buckets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
