#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Generate buckets.gen.h, buckets.sh, buckets.json from buckets.schema
set -e
ROOT="${1:-.}"
SCHEMA="$ROOT/package/openont/openont-stats/files/usr/share/openont/buckets.schema"
OUT_DIR="$ROOT/package/openont/openont-stats/files/usr/share/openont"
DPI_INC="$ROOT/package/openont/openont-dpi/src"
JS_OUT="$ROOT/package/openont/luci-mod-openont/htdocs/luci-static/resources/openont/buckets.json"

[ -f "$SCHEMA" ] || { echo "missing schema: $SCHEMA" >&2; exit 1; }
mkdir -p "$OUT_DIR" "$DPI_INC" "$(dirname "$JS_OUT")"

H="$OUT_DIR/buckets.gen.h"
SH="$OUT_DIR/buckets.sh"
JSON="$OUT_DIR/buckets.json"

# Collect rows
rows=""
while IFS= read -r line || [ -n "$line" ]; do
	case "$line" in
		''|\#*) continue ;;
	esac
	id=${line%%|*}; rest=${line#*|}
	name=${rest%%|*}; color=${rest#*|}
	[ -n "$id" ] && [ -n "$name" ] || continue
	rows="$rows$id|$name|$color
"
done < "$SCHEMA"

# --- C header ---
{
	echo "/* GENERATED by scripts/openont/gen-buckets.sh — do not edit */"
	echo "#ifndef OPENONT_BUCKETS_GEN_H"
	echo "#define OPENONT_BUCKETS_GEN_H"
	echo "#include <stdint.h>"
	echo "#define OPENONT_DPI_MARK_SHIFT 16"
	echo "#define OPENONT_DPI_MARK_MASK  0x00FF0000u"
	echo "enum oo_bucket_id {"
	echo "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		sym=$(echo "$name" | tr 'a-z' 'A-Z' | tr -c 'A-Z0-9' '_')
		echo "	OO_B_${sym} = ${id},"
	done
	echo "};"
	echo "static inline const char *oo_bucket_name(uint8_t id) {"
	echo "	switch (id) {"
	echo "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		echo "	case ${id}: return \"${name}\";"
	done
	echo "	default: return \"unknown\";"
	echo "	}"
	echo "}"
	echo "static inline uint8_t oo_bucket_id(const char *name) {"
	echo "	if (!name || !*name) return 0;"
	echo "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		echo "	if (name[0]=='${name%${name#?}}' && !strcmp(name, \"${name}\")) return ${id};"
	done
	# simpler strcmp chain without broken first-char hack:
	echo "	return 0;"
	echo "}"
	echo "#endif"
} > "$H.tmp"

# Fix oo_bucket_id properly (rewrite second half cleanly)
{
	echo "/* GENERATED by scripts/openont/gen-buckets.sh — do not edit */"
	echo "#ifndef OPENONT_BUCKETS_GEN_H"
	echo "#define OPENONT_BUCKETS_GEN_H"
	echo "#include <stdint.h>"
	echo "#include <string.h>"
	echo "#define OPENONT_DPI_MARK_SHIFT 16"
	echo "#define OPENONT_DPI_MARK_MASK  0x00FF0000u"
	echo "enum oo_bucket_id {"
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		sym=$(printf '%s' "$name" | tr 'a-z' 'A-Z')
		sym=$(printf '%s' "$sym" | sed 's/[^A-Z0-9]//_/g')
		printf '\tOO_B_%s = %s,\n' "$sym" "$id"
	done
	echo "};"
	echo "static inline const char *oo_bucket_name(uint8_t id)"
	echo "{"
	echo "	switch (id) {"
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		printf '\tcase %s: return "%s";\n' "$id" "$name"
	done
	echo "	default: return \"unknown\";"
	echo "	}"
	echo "}"
	echo "static inline uint8_t oo_bucket_id(const char *name)"
	echo "{"
	echo "	if (!name || !*name) return 0;"
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		printf '\tif (!strcmp(name, "%s")) return %s;\n' "$name" "$id"
	done
	echo "	return 0;"
	echo "}"
	echo "#endif"
} > "$H"

# --- shell ---
{
	echo "# GENERATED by scripts/openont/gen-buckets.sh — do not edit"
	echo "OPENONT_DPI_MARK_SHIFT=16"
	echo "OPENONT_DPI_MARK_MASK=0x00FF0000"
	echo "OPENONT_BUCKET_NAMES=\""
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		echo "$name"
	done
	echo "\""
	echo "openont_bid2name() {"
	echo "	case \"\$1\" in"
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		printf '\t\t%s) echo %s ;;\n' "$id" "$name"
	done
	echo "		*) echo unknown ;;"
	echo "	esac"
	echo "}"
} > "$SH"

# --- json (share + luci copy) ---
{
	echo "{"
	echo '  "mark_shift": 16,'
	echo '  "buckets": ['
	first=1
	printf '%s' "$rows" | while IFS='|' read -r id name color; do
		[ -z "$id" ] && continue
		if [ "$first" = 1 ]; then first=0; else echo ","; fi
		printf '    {"id":%s,"name":"%s","color":"%s"}' "$id" "$name" "$color"
	done
	echo ""
	echo "  ]"
	echo "}"
} > "$JSON"

# Fix JSON commas with a second pass (portable)
awk -F'|' '
BEGIN {
  print "{"
  print "  \"mark_shift\": 16,"
  print "  \"buckets\": ["
  n=0
}
/^#/ || NF < 2 { next }
{
  id=$1; name=$2; color=$3
  if (id == "" || name == "") next
  row[n]=sprintf("    {\"id\":%s,\"name\":\"%s\",\"color\":\"%s\"}", id, name, color)
  n++
}
END {
  for (i=0;i<n;i++) {
    printf "%s%s\n", row[i], (i<n-1?",":"")
  }
  print "  ]"
  print "}"
}
' "$SCHEMA" > "$JSON"

cp -f "$H" "$DPI_INC/buckets.gen.h"
cp -f "$JSON" "$JS_OUT"
cp -f "$JSON" "$OUT_DIR/buckets.json"
rm -f "$H.tmp" 2>/dev/null || true
echo "generated: $H $SH $JSON $DPI_INC/buckets.gen.h $JS_OUT"
