#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.OpenONT >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.OpenONT=/luci-static/openont
		set luci.main.mediaurlbase=/luci-static/openont
		commit luci
	EOF
fi

exit 0
