#!/bin/sh
# Always register and select OpenONT theme (first boot and package reinstall).

uci -q batch <<-EOF
	set luci.themes.OpenONT=/luci-static/openont
	set luci.main.mediaurlbase=/luci-static/openont
	delete luci.themes.Bootstrap
	delete luci.themes.OpenWrt
	commit luci
EOF

exit 0
