#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: Apache-2.0

START=98
USE_PROCD=1

start_service() {
	mkdir -p /tmp/openont-stats

	procd_open_instance appclass
	procd_set_param command /usr/sbin/openont-appclass
	procd_set_param respawn 3600 5 0
	procd_close_instance

	procd_open_instance statsd
	procd_set_param command /usr/sbin/openont-statsd
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
